---
- name: Mealie | Make sure Mealie path exists
  file:
    path: "{{ item }}"
    state: directory
    group: docker
    mode: u=rwX,g=rwX,o=rX
  become: true
  loop:
    - "{{ mealie__path }}"
    - "{{ mealie__path }}/backup"
    - "{{ mealie__run_path }}"

- name: Mealie | Copy docker-compose.yml
  template:
    src: docker-compose.j2
    dest: "{{ mealie__path }}/docker-compose.yml"
    group: docker
    mode: u=rw,g=rw,o=r
  become: true
  notify: Mealie | Restart Mealie

- name: Mealie | Pull image and start service
  community.docker.docker_compose:
    project_src: "{{ mealie__path }}"
    pull: yes
    state: present
  become: true

- name: Mealie | Copy backup script
  template:
    src: backup.sh
    dest: "{{ mealie__run_path }}/backup.sh"
    group: docker
    mode: u=rwx,g=rwx,o=r
  become: true

- name: Mealie | Set up database backup cron job
  cron:
    name: "mealie.backup/data"
    minute: "{{ mealie__backup_minute }}"
    hour: "{{ mealie__backup_hour }}"
    day: "{{ mealie__backup_day }}"
    month: "{{ mealie__backup_month }}"
    weekday: "{{ mealie__backup_weekday }}"
    job: >-
      /usr/bin/env sh {{ mealie__run_path }}/backup.sh
  become: true
