---
- name: Grafana | Make sure Grafana datasources path exists
  file:
    path: "{{ grafana__path }}/provisioning/datasources"
    state: directory
    group: docker
    mode: u=rwX,g=rwX,o=rX
  become: true

- name: Grafana | Make sure Grafana provisioning path exists
  file:
    path: "{{ grafana__path }}/provisioning/dashboards"
    state: directory
    group: docker
    mode: u=rwX,g=rwX,o=rX
  become: true

- name: Grafana | Copy docker-compose.yml
  template:
    src: docker-compose.j2
    dest: "{{ grafana__path }}/docker-compose.yml"
    group: docker
    mode: u=rw,g=rw,o=r
  become: true
  notify: Grafana | Restart Grafana

- name: Grafana | Copy grafana.ini
  template:
    src: grafana.j2
    dest: "{{ grafana__path }}/grafana.ini"
    group: docker
    mode: u=rw,g=rw,o=r
  become: true
  notify: Grafana | Restart Grafana

- name: Grafana | Copy datasource.yml
  template:
    src: datasource.j2
    dest: "{{ grafana__path }}/provisioning/datasources/datasource.yml"
    group: docker
    mode: u=rw,g=rw,o=r
  become: true
  notify: Grafana | Restart Grafana

- name: Grafana | Copy dashboards.yml
  template:
    src: dashboard.j2
    dest: "{{ grafana__path }}/provisioning/dashboards/dashboard.yml"
    group: docker
    mode: u=rw,g=rw,o=r
  become: true
  notify: Grafana | Restart Grafana

- name: Grafana | Copy dashboard definitions
  copy:
    src: dashboards
    dest: "{{ grafana__path }}/provisioning"
    group: docker
    mode: u=rwX,g=rwX,o=rX
  become: true
  notify: Grafana | Restart Grafana

- name: Grafana | Pull image and start service
  ansible.builtin.command: docker compose up --detach
  args:
    chdir: "{{ grafana__path }}"
  become: true
