---

- name: Watchtower | Make sure Watchtower path exists
  file:
    path: "{{ watchtower__path }}"
    state: directory
    group: docker
    mode: u=rwX,g=rwX,o=rX
  become: true

- name: Watchtower | Copy docker-compose.yml
  template:
    src: docker-compose.j2
    dest: "{{ watchtower__path }}/docker-compose.yml"
    group: docker
    mode: u=rw,g=rw,o=r
  become: true
  notify: Watchtower | Restart Watchtower

- name: Watchtower | Pull image and start service
  ansible.builtin.command: docker compose up --detach
  args:
    chdir: "{{ watchtower__path }}"
  become: true
