---
# Deploy Caddy config

- name: Caddy | Config | Make sure path exists
  file:
    path: "{{ caddy__path }}"
    state: directory
    mode: u=rwx,g=rx,o=rx
  become: yes

- name: Caddy | Config | Deploy Caddyfile
  template:
    src: Caddyfile.j2
    dest: "{{ caddy__path }}/Caddyfile"
    mode: u=rw,g=r,o=r
  become: yes
