---
# Deploy Caddy config

- name: Caddy | Config | Make sure caddy path exists
  file:
    path: "{{ caddy__path }}"
    state: directory
    group: docker
    mode: u=rwx,g=rwx,o=rx
  become: true

- name: Caddy | Config | Make sure serve path exists
  file:
    path: "{{ caddy__srv_path }}"
    state: directory
    group: docker
    mode: u=rwx,g=rwx,o=rx
  become: true

- name: Caddy | Config | Deploy Caddyfile
  template:
    src: Caddyfile.j2
    dest: "{{ caddy__path }}/Caddyfile"
    group: docker
    mode: u=rw,g=rw,o=r
  become: true
  notify: Caddy | Restart Caddy
