---
# Deploy Caddy config

- name: Caddy | Config | Make sure path exists
  file:
    path: "{{ caddy__path }}"
    state: directory
    group: docker
    mode: u=rwx,g=rwx,o=rx
  become: yes

- name: Caddy | Config | Deploy Caddyfile
  template:
    src: Caddyfile.j2
    dest: "{{ caddy__path }}/Caddyfile"
    group: docker
    mode: u=rw,g=rw,o=r
  become: yes
  notify: Caddy | Restart Caddy
