---

- name: Caddy | Config
  import_tasks: config.yml

- name: Caddy | Docker
  import_tasks: docker.yml

- name: Docker | Set up ufw rules
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  become: true
  loop:
    - http
    - https
