---

- name: Caddy | Config
  include_tasks: config.yml

- name: Caddy | Docker
  include_tasks: docker.yml

- name: Docker | Set up ufw rules
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  become: yes
  with_items:
    - http
    - https
