galaxy_info:
  role_name: seafile
  author: stehessel
  description: Ansible role to set up seafile
  license: BSD-3-Clause
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
  galaxy_tags:
    - cloud
    - filesync
dependencies: []
