---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ufw"
      include_role:
        name: "stehessel.server.ufw"

    - name: "Include docker"
      include_role:
        name: "stehessel.server.docker"

    - name: "Include caddy"
      include_role:
        name: "stehessel.server.caddy"
      vars:
        caddy__services:
          domain: example.com
          type: file_server
        docker__cgroup_parent: "/actions_job"
        docker__storage_driver: "vfs"
