---

- name: init | Set clock to hardware clock
  command: hwclock --systohc
  become: true
  listen: timezone changed

- name: init | Restart sshd
  service:
    name: sshd
    state: restarted
  become: true
  listen: restart sshd
