---

- import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: ufw | Install package
  package:
    name: ufw
    state: present
  become: true

- name: ufw | Start and enable service
  community.general.ufw:
    state: enabled
  become: true

- name: ufw | Allow ansible port
  community.general.ufw:
    rule: allow
    port: "{{ ansible_port }}"
    proto: tcp
  become: true

- name: ufw | Create rules
  community.general.ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.protocol | default('any') }}"
  loop: "{{ ufw__rules }}"
  become: true
