galaxy_info:
  role_name: grafana
  author: stehessel
  description: Ansible role to set up Grafana
  license: BSD-3-Clause
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
  galaxy_tags:
    - dashboards
    - grafana
    - monitoring
    - observability
dependencies: []
