---
- name: Converge
  hosts: all
  tasks:
    - name: "Include docker"
      include_role:
        name: "stehessel.server.docker"

    - name: "Include Prometheus"
      include_role:
        name: "stehessel.server.prometheus"
