---
- name: Converge
  hosts: all
  tasks:
    - name: "Include docker"
      include_role:
        name: "stehessel.server.docker"

    - name: "Include Watchtower"
      include_role:
        name: "stehessel.server.watchtower"
