---
- name: Papermerge | Make sure Papermerge path exists
  file:
    path: "{{ item }}"
    state: directory
    group: docker
    mode: u=rwX,g=rwX,o=rX
  become: yes
  loop:
    - "{{ papermerge__path }}"
    - "{{ papermerge__path }}/backup"
    - "{{ papermerge__path }}/media"

- name: Papermerge | Copy docker files
  copy:
    src: ./
    dest: "{{ papermerge__path }}"
    group: docker
    mode: u=rwX,g=rwX,o=rX
  become: yes
  notify: Papermerge | Restart Papermerge

- name: Papermerge | Copy docker-compose.yml
  template:
    src: docker-compose.j2
    dest: "{{ papermerge__path }}/docker-compose.yml"
    group: docker
    mode: u=rw,g=rw,o=r
  become: yes
  notify: Papermerge | Restart Papermerge

- name: Papermerge | Pull image and start service
  community.docker.docker_compose:
    project_src: "{{ papermerge__path }}"
    pull: yes
    state: present
  become: yes

- name: Papermerge | Set up database backup cron job
  cron:
    name: "papermerge.backup/postgres"
    minute: "{{ papermerge__backup_minute }}"
    hour: "{{ papermerge__backup_hour }}"
    day: "{{ papermerge__backup_day }}"
    month: "{{ papermerge__backup_month }}"
    weekday: "{{ papermerge__backup_weekday }}"
    job: >-
      docker exec -t papermerge_db pg_dumpall -c -U dbuser > {{ papermerge__path }}/backup/dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql
  become: yes
