---
- name: Converge
  hosts: all
  tasks:
    - name: "Include docker"
      include_role:
        name: "stehessel.server.docker"

    - name: "Create Caddy network"
      community.docker.docker_network:
        name: caddy-net
      become: true

    - name: "Include buku"
      include_role:
        name: "stehessel.server.buku"
