---
- name: Prometheus | Make sure Prometheus path exists
  file:
    path: "{{ prometheus__path }}"
    state: directory
    group: docker
    mode: u=rwx,g=rwx,o=rx
  become: true

- name: Prometheus | Copy docker-compose.yml
  template:
    src: docker-compose.j2
    dest: "{{ prometheus__path }}/docker-compose.yml"
    group: docker
    mode: u=rw,g=rw,o=r
  become: true
  notify: Prometheus | Restart Prometheus

- name: Prometheus | Copy prometheus.yml
  template:
    src: prometheus.j2
    dest: "{{ prometheus__path }}/prometheus.yml"
    group: docker
    mode: u=rw,g=rw,o=r
  become: true
  notify: Prometheus | Restart Prometheus

- name: Prometheus | Pull image and start service
  ansible.builtin.command: docker compose up --detach
  args:
    chdir: "{{ prometheus__path }}"
  become: true
