---

- name: Docker | Add Users | Create "docker" group
  group:
    name: docker
    state: present
  become: true

- name: Docker | Add Users | Add users to "docker" group
  user:
    name: "{{ item }}"
    groups:
      - docker
    append: yes
  become: true
  loop: "{{ docker__users }}"
  when: docker__users is defined

# Allow changes for current user
- name: Docker | Add User | Reset ssh connection
  meta: reset_connection
