---

- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Docker | Install packages
  package:
    name:
      - "{{ docker__package }}"
      - docker-compose
    state: "{{ docker__state }}"
  become: yes

- name: Docker | Start and enable service
  service:
    name: docker
    enabled: "{{ docker__service_enabled }}"
    state: started
  become: yes

- name: Docker | Config
  include_tasks: config.yml

- name: Docker | Add users
  include_tasks: add_users.yml

- name: Docker | Cron jobs
  include_tasks: cron.yml

- name: Docker | Set up ufw rules
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  become: yes
  with_items:
    - http
    - https

