---
- import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Docker | Install packages
  package:
    name:
      - "{{ docker__package }}"
      - docker-compose
    state: "{{ docker__state }}"
  become: true

- name: Docker | Start and enable service
  service:
    name: docker
    enabled: "{{ docker__service_enabled }}"
    state: started
  become: true

- name: Docker | Config
  import_tasks: config.yml

- name: Docker | Add users
  import_tasks: add_users.yml

- name: Docker | Cron jobs
  import_tasks: cron.yml
