---
- name: Converge
  hosts: all
  tasks:
    - name: "Include docker"
      include_role:
        name: "stehessel.server.docker"
      vars:
        docker__users:
          - sudouser
        docker__cgroup_parent: "/actions_job"
        docker__storage_driver: "vfs"
