---

- name: Buku | Make sure buku path exists
  file:
    path: "{{ buku__path }}"
    state: directory
    group: docker
    mode: u=rwX,g=rwX,o=rX
    recurse: yes
  become: true

- name: Buku | Copy docker-compose.yml
  template:
    src: docker-compose.j2
    dest: "{{ buku__path }}/docker-compose.yml"
    group: docker
    mode: u=rw,g=rw,o=r
  become: true
  notify: buku | Restart buku

- name: Buku | Pull image and start service
  ansible.builtin.command: docker compose up --detach
  args:
    chdir: "{{ buku__path }}"
  become: true
