---
- name: Syncthing | Make sure Syncthing path exists
  file:
    path: "{{ syncthing__path }}"
    state: directory
    group: docker
    mode: u=rwX,g=rwX,o=rX
  become: true

- name: Syncthing | Copy docker-compose.yml
  template:
    src: docker-compose.j2
    dest: "{{ syncthing__path }}/docker-compose.yml"
    group: docker
    mode: u=rw,g=rw,o=r
  become: true
  notify: Syncthing | Restart Syncthing

- name: Syncthing | Pull image and start service
  ansible.builtin.command: docker compose up --detach
  args:
    chdir: "{{ syncthing__path }}"
  become: true

- name: Docker | Set up ufw rules
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.protocol }}"
  become: true
  loop:
    - port: 22000
      protocol: tcp
    - port: 22000
      protocol: udp
    - port: 21027
      protocol: udp
