---

- name: init | Set up timesync
  import_tasks: timesync.yml

- name: init | Set locale
  locale_gen:
    name: "{{ init__locale }}"
    state: present

- name: init | Setup hosts file
  blockinfile:
    path: /etc/hosts
    block: |
      127.0.0.1     localhost
      ::1           localhost
      127.0.0.1     "{{ init__host_name }}.{{ init__domain_name }}"
  become: true

- name: init | Set up users
  import_tasks: users.yml

- name: init | Set up ssh
  import_tasks: ssh.yml

- name: init | Install packages
  package:
    name:
      - htop
      - neovim
      - which
    state: present
  become: true
