galaxy_info:
  role_name: docker
  author: stehessel
  description: Ansible role to install docker
  license: BSD-3-Clause
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
        - focal
  galaxy_tags:
    - docker
dependencies: []
